language: php

mysql:
  database: testlink_test
  username: root
  encoding: utf8

before_install:
  - composer self-update

#
install:
  # install TestLink
  # - git clone https://github.com/TestLinkOpenSourceTRMS/testlink-code.git

  # TBD - TestLink final deployment

  # install selenium
  - composer install

  # Download and run server version.
  - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar
  - java -jar selenium-server-standalone-2.48.2.jar -htmlSuite *firefox -log selenium.log &

  - ls -la vendor

# Custom PHP configuration #
before_script:
  - phpenv config-add myconfig.ini

  # create new db, set up configuration parameters
  - mysql -e 'create database testlink_test'

  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - php -S localhost:8000 -t public/ &

script: phpunit --verbose -c tests/phpunit.xml

after_script:
  - cat selenium.log