language: php

mysql:
  database: testlink_test
  username: root
  encoding: utf8

#
install:
  - git clone https://github.com/TestLinkOpenSourceTRMS/testlink-code.git
  - ls -la /home/travis/build/marcel-veselka/testlink-qa/Tests/

  # install selenium
  - composer install

  # Download and run server version.
  - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar
  - java -jar selenium-server-standalone-2.48.2.jar -log selenium.log &

# Custom PHP configuration #
before_script:
  - phpenv config-add myconfig.ini

  # create new db, set up configuration parameters
  - mysql -e 'create database testlink_test'

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
# script: phpunit --configuration phpunit_mysql.xml --coverage-text
script: phpunit --configuration phpunit_mysql.xml

